In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification

In [2]:
X,y=make_classification(n_samples=100,n_features=6,n_informative=3,n_classes=2)

In [3]:
data={f'Feature {i+1}':X[:,i] for i in range(6)}
data['Target']=y
df=pd.DataFrame(data)

In [4]:
df.head()

Feature 1  Feature 2  Feature 3  Feature 4  Feature 5  Feature 6  Target
0   2.291973   1.822320   3.407057  -1.782991   0.793156   3.255425       0
1  -0.182513  -0.616288  -2.047341  -1.567431   1.951696  -1.845331       1
2  -1.895178  -0.432679   0.987165   2.032253   0.093508   1.321793       0
3   1.748171   0.088824   1.831070  -1.452828   0.421621   1.669284       0
4  -0.814739   1.602493   1.691652   1.278398  -0.067395   1.861762       0

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model=Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=6))
model.add(Dense(1,activation='sigmoid'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 21        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 25 (100.00 Byte)
Trainable params: 25 (100.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.get_weights()

[array([[ 0.632913  ,  0.08129567, -0.15762365],
        [-0.7827026 , -0.6298149 , -0.7424597 ],
        [-0.5165343 ,  0.8137654 ,  0.622416  ],
        [-0.04839385, -0.42679745,  0.29660177],
        [-0.65076274, -0.45061448, -0.57621855],
        [-0.30374295, -0.23063093,  0.36147308]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.90694606],
        [ 0.9000989 ],
        [-1.0447464 ]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [10]:
model.fit(df.iloc[:,0:-1].values,df['Target'].values,epochs=100,batch_size=1,verbose=1)

Epoch 1/100
100/100 [==============================] - 1s 3ms/step - loss: 0.7007
Epoch 2/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6810
Epoch 3/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6642
Epoch 4/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6500
Epoch 5/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6371
Epoch 6/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6255
Epoch 7/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6157
Epoch 8/100
100/100 [==============================] - 0s 3ms/step - loss: 0.6073
Epoch 9/100
100/100 [==============================] - 0s 3ms/step - loss: 0.5993
Epoch 10/100
100/100 [==============================] - 0s 3ms/step - loss: 0.5924
Epoch 11/100
100/100 [==============================] - 0s 3ms/step - loss: 0.5857
Epoch 12/100
100/100 [==============================] - 0s 3ms/step - loss: 0.5802
Epoch 13/100
