In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_regression

In [2]:
X,y=make_regression(n_samples=100,n_features=3,noise=0)

In [3]:
data = {f'Feature_{i+1}': X[:, i] for i in range(3)}
data['Target'] = y
df = pd.DataFrame(data)

In [4]:
df.head()

Feature_1  Feature_2  Feature_3      Target
0   1.182112  -1.095190   1.379006  167.066853
1   0.936024   0.994414   1.221445  197.922566
2   1.570824   0.140745   1.139033  221.126048
3  -1.643531  -0.287202   0.389445 -123.274479
4   0.599561  -1.319538  -1.211475  -74.177870

In [5]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [16]:
model=Sequential()

model.add(Dense(3,activation='linear',input_dim=3))
model.add(Dense(2,activation='linear',input_dim=3))
model.add(Dense(1,activation='linear'))

In [17]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 3)                 12        
                                                                 
 dense_5 (Dense)             (None, 2)                 8         
                                                                 
 dense_6 (Dense)             (None, 1)                 3         
                                                                 
Total params: 23 (92.00 Byte)
Trainable params: 23 (92.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.get_weights()

[array([[-9.1310787e-01, -2.1420336e-01, -1.8453550e-01],
        [-9.5844269e-04,  8.8632345e-01, -1.0546780e-01],
        [-3.7304473e-01,  9.9704742e-01,  9.6339440e-01]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[-0.8951042 , -0.6553019 ],
        [-0.65656024, -0.02117682],
        [ 0.82027173, -0.51484513]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0226542],
        [ 0.6000215]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [20]:
model.fit(df.iloc[:,0:-1].values,df['Target'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100
100/100 [==============================] - 1s 2ms/step - loss: 15362.5225
Epoch 2/100
100/100 [==============================] - 0s 2ms/step - loss: 15273.2559
Epoch 3/100
100/100 [==============================] - 0s 2ms/step - loss: 15187.7041
Epoch 4/100
100/100 [==============================] - 0s 2ms/step - loss: 15097.1934
Epoch 5/100
100/100 [==============================] - 0s 2ms/step - loss: 14992.7451
Epoch 6/100
100/100 [==============================] - 0s 2ms/step - loss: 14857.2100
Epoch 7/100
100/100 [==============================] - 0s 2ms/step - loss: 14678.5566
Epoch 8/100
100/100 [==============================] - 0s 2ms/step - loss: 14438.0889
Epoch 9/100
100/100 [==============================] - 0s 2ms/step - loss: 14114.7988
Epoch 10/100
100/100 [==============================] - 0s 2ms/step - loss: 13696.9365
Epoch 11/100
100/100 [==============================] - 0s 2ms/step - loss: 13178.2686
Epoch 12/100
100/100 [==============================

100/100 [==============================] - 0s 3ms/step - loss: 5.3310e-09
Epoch 97/100
100/100 [==============================] - 0s 3ms/step - loss: 4.1868e-09
Epoch 98/100
100/100 [==============================] - 0s 3ms/step - loss: 3.7747e-09
Epoch 99/100
100/100 [==============================] - 0s 3ms/step - loss: 3.9009e-09
Epoch 100/100
100/100 [==============================] - 0s 3ms/step - loss: 3.4916e-09


In [21]:
model.get_weights()

[array([[-2.8120582 ,  1.8270596 , -2.1659365 ],
        [-0.33225408,  1.3991311 , -0.5148203 ],
        [-1.9214072 ,  2.7903094 , -0.69657797]], dtype=float32),
 array([0.00354051, 0.00290874, 0.0016526 ], dtype=float32),
 array([[ 1.202595 , -2.8239276],
        [-2.7038934,  2.0941548],
        [ 2.3005855, -2.0109298]], dtype=float32),
 array([-0.00217387,  0.00355181], dtype=float32),
 array([[-3.0245802],
        [ 2.8717356]], dtype=float32),
 array([0.00455923], dtype=float32)]